version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123dynamicweb
      - POSTGRES_DB=dynamicweb
    ports:
      - "5434:5432"
    networks:
      - dynamicweb-net

networks:
  dynamicweb-net:
